name: Setup Build Environment
description: Setup Python/Brownie/NodeJS Development Environment for PR/Build Tasks
inputs:
  poetry_version:
    description: Version of Poetry to Install
    required: false
    default: 1.1.11
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        pip install poetry==${{ inputs.poetry_version }}
      shell: bash
    - run: |
        npm install -g ganache-cli
    - run: |
        poetry update
      shell: bash
    - run: |
        poetry run brownie pm install OpenZeppelin/openzeppelin-contracts@4.3.0
      shell: bash
    - run: |
        poetry run brownie compile --all
      working-directory: ./contracts
      shell: bash
